<a href="https://colab.research.google.com/github/ayu69hub/machine-learning/blob/main/traning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded = files.upload()

Saving train.nlp (1).txt to train.nlp (1).txt

In [3]:
df = pd.read_csv('train.nlp (1).txt',sep=';',header=None,names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
unique_emotions = df['emotion'].unique()
emotions_number ={}
i=0
for emo in unique_emotions:
  emotions_number[emo]=i
  i+=1

df['emotion'] = df['emotion'].map(emotions_number)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
df['text']=df['text'].apply(lambda x:x.lower())

In [9]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [10]:
df['text']=df['text'].apply(remove_punc)

In [11]:
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new
df['text'] = df['text'].apply(remove_numbers)

In [12]:
from os import remove
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new+=i
  return new
df['text']= df['text'].apply(remove_emojis)

In [13]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [14]:
stop_words = set(stopwords.words('english'))
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)


df['text']= df['text'].apply(remove)

In [15]:

df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['text'],df['emotion'],test_size = 0.20, random_state=42)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [18]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [19]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [20]:
nb_model = MultinomialNB()

In [21]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [23]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.768125

In [24]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [25]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [26]:
y_pred = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))

0.6609375

In [27]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [28]:
log_pred = lr_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred))

0.8628125

In [31]:
import joblib

joblib.dump(lr_model, '/content/drive/MyDrive/traning.pkl')

['/content/drive/MyDrive/traning.pkl']